// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MoodleExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMoodleExtensionPackageString = "ca202ab6-3b94-4f91-bb25-2d624a787312";
        public const string guidMoodleExtensionPackageCmdSetString = "9ee3b308-bcd7-4b67-8009-0276c2aee113";
        public const string guidImagesString = "bc5b87fd-5133-4c28-949b-2ef84a23dea2";
        public const string guidImages1String = "0b29ec61-46f4-4ffd-867a-796a4c29c12b";
        public static Guid guidMoodleExtensionPackage = new Guid(guidMoodleExtensionPackageString);
        public static Guid guidMoodleExtensionPackageCmdSet = new Guid(guidMoodleExtensionPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorContextMenuGroup = 0x1020;
        public const int cmdidEnableDisableMoodleExtensionCommand = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
